### PR TITLE
[RFR] Remove except-pass as a required check in pylint-odoo config

### PR DESCRIPTION
**Pull request by StefanRijnhart**
See https://github.com/OCA/pylint-odoo/issues/361

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]
Thanks.

**Review by pedrobaeza — APPROVED** [review]

**Review by sbidoul — APPROVED** [review]

**Comment by StefanRijnhart** [comment]
With @yajo offering the alterative of using `contextlib.suppress` on the pylint-odoo ticket, do we want to proceed with this? I can add a line about this to https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#39exceptions.

**Comment by Yajo** [comment]
Seems a better fix IMHO.

Actually those docs say: *The pass into block except is not a good practice!* but there's no explanation whatsoever, so in any case they can be improved.

**Comment by legalsylvain** [comment]
@StefanRijnhart is it this PR really in draft state ?

**Pull request closed without merging**
