### PR TITLE
[FIX][15.0] branches Update flake8 autoflake

### PR DESCRIPTION
**Pull request by bosd**
Fixes 15.0 branches:

As spotted in 15.0 branch of https://github.com/OCA/stock-logistics-warehouse/tree/15.0
job: https://github.com/OCA/stock-logistics-warehouse/actions/runs/6711504373/job/18239016420
CI on 15.0 PR are red.

autoflake
```
Traceback (most recent call last):
  File "/home/bosd/.cache/pre-commit/repop6v3fone/py_env-python3/bin/autoflake", line 5, in <module>
    from autoflake import main
  File "/home/bosd/.cache/pre-commit/repop6v3fone/py_env-python3/lib/python3.12/site-packages/autoflake.py", line 32, in <module>
    import distutils.sysconfig
ModuleNotFoundError: No module named 'distutils'

````

flake8

```
Traceback (most recent call last):
  File "/home/bosd/.cache/pre-commit/repo1vkztq8l/py_env-python3/bin/flake8", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/bosd/.cache/pre-commit/repo1vkztq8l/py_env-python3/lib/python3.12/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/home/bosd/.cache/pre-commit/repo1vkztq8l/py_env-python3/lib/python3.12/site-packages/flake8/main/application.py", line 363, in run
    self._run(argv)
  File "/home/bosd/.cache/pre-commit/repo1vkztq8l/py_env-python3/lib/python3.12/site-packages/flake8/main/application.py", line 350, in _run
    self.initialize(argv)
  File "/home/bosd/.cache/pre-commit/repo1vkztq8l/py_env-python3/lib/python3.12/site-packages/flake8/main/application.py", line 330, in initialize
    self.find_plugins(config_finder)
  File "/home/bosd/.cache/pre-commit/repo1vkztq8l/py_env-python3/lib/python3.12/site-packages/flake8/main/application.py", line 153, in find_plugins
    self.check_plugins = plugin_manager.Checkers(local_plugins.extension)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bosd/.cache/pre-commit/repo1vkztq8l/py_env-python3/lib/python3.12/site-packages/flake8/plugins/manager.py", line 356, in __init__
    self.manager = PluginManager(
                   ^^^^^^^^^^^^^^
  File "/home/bosd/.cache/pre-commit/repo1vkztq8l/py_env-python3/lib/python3.12/site-packages/flake8/plugins/manager.py", line 238, in __init__
    self._load_entrypoint_plugins()
  File "/home/bosd/.cache/pre-commit/repo1vkztq8l/py_env-python3/lib/python3.12/site-packages/flake8/plugins/manager.py", line 254, in _load_entrypoint_plugins
    eps = importlib_metadata.entry_points().get(self.namespace, ())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'EntryPoints' object has no attribute 'get'


```

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please put a link to a CI job with such problem.

**Comment by bosd** [comment]
https://github.com/OCA/stock-logistics-warehouse/actions/runs/6711504373/job/18239016420

**Review by zamberjo — APPROVED** [review]
This Pr fixes https://github.com/OCA/oca-addons-repo-template/issues/257

**Review by Dranyel-Bosd — APPROVED** [review]
LGTM 👍♥️

**Comment by pedrobaeza** [comment]
The referred PR was merged, so isn't this something specific on your side due to newer Python?

**Comment by bosd** [comment]
I assume you're referring to this:
In that pr I did a manual overwrite.



Repo template may need update as well.  https://github.com/OCA/oca-addons-repo-template/pull/243

_Originally posted by @bosd in https://github.com/OCA/stock-logistics-warehouse/pull/1913#issuecomment-1890566297_

**Comment by zamberjo** [comment]
This is unnecessary, updating maintainer-tools to f81a2cd8b3e7ba06d96a6fc8c944e6c7174faf7f will fix it: 
https://github.com/OCA/maintainer-tools/pull/618

**Review by OpenCode — APPROVED** [review]

**Review by OpenCode — APPROVED** [review]

**Comment by florian-dacosta** [comment]
Hello,
The problem exists and it does not depend on Odoo's version, so we would need to update the flake8 for Odoo version < 15 as well.

The problem happends when you run pre-commit with an up-to-date python version (python 3.12 in my case) as it is not compatible with flake8  3.9.2
It depends on the python version of the host running pre-commit.
We do not see it on the CI because the CI runs on older python version for Odoo < 18
And for odoo 18, there is not flake 3.9.2...

I have this issue for almost all OCA repo for version 14, 16...
@sbidoul

**Comment by bosd** [comment]
Should we merge this?
We have one person who doesn't need it. But others approving the pr and say it is needed.

**Comment by florian-dacosta** [comment]
@bosd Can you conflict ?
I believe the flake8 version should also be updated in this part
`{%- if odoo_version < 15 %}`

**Comment by bosd** [comment]
@florian-dacosta Done. Rebased and added the update for <v15

**Comment by bosd** [comment]
just force pushed again. Because actions is/was adding a test it cannot complete.
image

**Review by Saran440 — APPROVED** [review]

**Comment by bosd** [comment]
Indeed this pr is still needed as in: https://github.com/OCA/sale-workflow/pull/3411

**Comment by sbidoul** [comment]
The risk with this PR is that the new flake8 version will have new rules that make existing branches red on many repos. That is why we pin the versions of the hooks.

The other approach is to set the python version in the pre-commit config (something like https://github.com/OCA/oca-addons-repo-template/pull/282) but then devs need to install multiple version. This is my personal preference, because nowadays it is easier and faster than ever to install different python versions with tools such as [mise](https://github.com/jdx/mise) or [uv](https://docs.astral.sh/uv/).

And there is also the [nix](https://github.com/OCA/oca-addons-repo-template/issues/175) approach which I have not evaluated in details. The drawback of that one is that it seem to be more complex to setup.

**Review by yajo — APPROVED** [review]
> The risk with this PR is that the new flake8 version will have new rules that make existing branches red on many repos. That is why we pin the versions of the hooks.

I don't think this is a big problem nowadays.

If you update the template, *then* you'll get the error. But templates are not auto-updated. Thus, there's no risk to having a bomb of ❌ in our repos (unless we mass-update the template, which is not done very often).

I vote to merge this.

**Comment by yajo** [comment]
This PR has 5 approvals already, so I guess it'll be better to merge it.

If things go wrong, chances are that updating the flake8 config file will fix the problem. I'll merge so we can update some repos with `-r HEAD` and see if all works. Otherwise we can open a new issue and fix it, or roll this back if it gives more problems than solves.

Thanks everyone!

**Pull request merged**
