### PR TITLE
build(pylint-odoo): bump for v16

### PR DESCRIPTION
**Pull request by yajo**
Fixes the problem explained in https://github.com/OCA/report-print-send/pull/328#discussion_r1209478993.

### CODE REVIEW

**Comment by legalsylvain** [comment]
Test are failing, (or are cancelled). could you check ?

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by legalsylvain — APPROVED** [review]
LGTM !

**Comment by sbidoul** [comment]
Can we do that major version bump of pylint-odoo without risk? Are there not some checks that are removed from pylint-odoo 8 and moved to another project?

**Comment by yajo** [comment]
@moylop260 told me to do it, and he maintains the project, so I guess he knows what he says 😉 

But well, friend could you please answer @sbidoul's doubt? Thanks!

**Review by legalsylvain — CHANGES_REQUESTED** [review]
Waiting for @moylop260 answer, regarding @sbidoul remark that is legit.

**Comment by sbidoul** [comment]
@StefanRijnhart the new checks are in https://github.com/OCA/odoo-pre-commit-hooks/.

**Comment by sbidoul** [comment]
@StefanRijnhart these new checks are not in this template yet AFAIK.

If we bump pylint-odoo to >=8, we need to add odoo-pre-commit-hooks to our .precommit-config.yaml, but we may also need to configure it to make sure we don't add new checks that would make existing branches red.

**Comment by StefanRijnhart** [comment]
Tests fail because we lost support for Python 2.7

> The support for python 2.7 will be removed on June 19. Related issue: https://github.com/actions/setup-python/issues/672

**Comment by StefanRijnhart** [comment]
Thanks @sbidoul for confirming! Any chance @yajo you could include the inclusion of the new linter here?

**Comment by yajo** [comment]
Added.

**Comment by micheledic** [comment]
Any news? i d like to implement https://github.com/OCA/report-print-send/pull/328

**Comment by isserver1** [comment]
Can we provide any assistance to make it merged?

**Comment by StefanRijnhart** [comment]
I ran this new pre-commit on [all 16.0 OCA branches](https://gist.github.com/StefanRijnhart/b6c5c258d453a3a484d071d312407012) and I did not spot a large number of issues raised by it. In my comment above I suggested to adjust the indentation in the jinja template but I noticed that the template still leaves an empty line in the yaml configuration file that pre-commit will want to clean up anyway. That makes me less interested in fixing the indentation.

If anybody wants to double check, here is the output of the pre-commit run: 
[pre-commit-16-all.txt.zip](https://github.com/OCA/oca-addons-repo-template/files/12113238/pre-commit-16-all.txt.zip)

**Review by StefanRijnhart — APPROVED** [review]

**Comment by yajo** [comment]
FWIW you don't have to be so much afraid of deploying changes to the template.

Remember: it's not like in the old days. Repo per repo, branch per branch, once the template is updated, if anything is violating a new linter, it will raise a ❌.

It's not like we're deploying a massive change by merging this.

**Comment by pedrobaeza** [comment]
Is the CI failing something expected?

**Comment by StefanRijnhart** [comment]
@yajo Well, I liked to have this confirmed before I took the responsability and approved this change.

@pedrobaeza Yes, Python 2.7 is gone. An attempt to revive it is https://github.com/OCA/oca-addons-repo-template/pull/199.

**Comment by pedrobaeza** [comment]
But seems to be not enough. Should we disable such CI?

**Comment by yajo** [comment]
I have removed the requirement for py2.7 job to allow unblocking this situation until properly fixed.

**Comment by micheledic** [comment]
tests ok, i guess should be merged, correct ?

**Comment by pedrobaeza** [comment]
It seems the test is still red.

**Comment by micheledic** [comment]
> It seems the test is still red.

The First test Is Red because there Is not support Fort python 2.7, i Guess It Is ok

**Comment by StefanRijnhart** [comment]
@pedrobaeza Appreciating that there is already an initiative to get this test green again I think keeping it in its current red state is fine.

**Comment by pedrobaeza** [comment]
I understood that @yajo remove such red. Should we merge with the red condition then?

**Comment by StefanRijnhart** [comment]
@yajo removed the `fail fast` attribute which makes it possible to check the outcome of the other tests when the 2.7 test fails, which suffices.

**Comment by pedrobaeza** [comment]
OK, I merge then.

**Comment by yajo** [comment]
I removed the python 2.7 from the requirements to merge PRs, that's why you were able to merge 😉

**Comment by micheledic** [comment]
Hello,
we need a new tag so we can update copier template on repos

**Comment by yajo** [comment]
https://github.com/OCA/oca-addons-repo-template/releases/tag/v1.15.0

**Comment by micheledic** [comment]
Updated report-print-send template
https://github.com/OCA/report-print-send/pull/334

**Pull request merged**
