### PR TITLE
[FIX] isort: started breaking the world today

### PR DESCRIPTION
**Pull request by yajo**
See PyCQA/isort#2077 and PyCQA/isort#2078 which are fixed by this release.

In https://github.com/OCA/l10n-spain/pull/2788 you can see this fixes the build.

### CODE REVIEW

**Comment by yajo** [comment]
Let me do a release.

**Comment by sbidoul** [comment]
@yajo can you also do it in https://github.com/OCA/oca-addons-repo-template/tree/master/version-specific ?

**Comment by pedrobaeza** [comment]
AFAIK, that versions are not affected. Only v15 and updated v16.

**Comment by yajo** [comment]
Yes, I think so. I ran some v14 jobs yesterday and they worked. But if you get the failure in old branches please ping me.

**Comment by SirTakobi** [comment]
> Yes, I think so. I ran some v14 jobs yesterday and they worked. But if you get the failure in old branches please ping me.

I'm having this error in `14.0`, see https://github.com/OCA/l10n-italy/actions/runs/4292864374/jobs/7479826720#step:7:77

**Comment by yajo** [comment]
Please upgrade the template

**Pull request merged**
