### PR TITLE
Set language_version for prettier

### LINKED ISSUE #15: prettier requires at least version 10.13.0 of Node, please upgrade
Example [here](https://travis-ci.com/github/OCA/mis-builder/jobs/396016494#L329-L330).

Does @Yajo or anyone know the fix for that?

### PR DESCRIPTION
**Pull request by sbidoul**
The default available on travis is too old.

fixes #15

### CODE REVIEW

**Comment by Yajo** [comment]
Cool! I was trying to help @ernestotejeda to fix this the other day and didn't have a clue...

Do you think it'd make more sense to update the `default_language_version` instead for `node`, just like we have for `python`?

**Comment by sbidoul** [comment]
> Do you think it'd make more sense to update the default_language_version instead for node, just like we have for python?

Ok, I'll try that. It's probably more coherent to have the same node version for all hooks that need it.

**Comment by Yajo** [comment]
Yes, that's what I thought.

**Comment by sbidoul** [comment]
Gah, now tests fails here on poetry install...

**Comment by Yajo** [comment]
Possibly a cache problem. I need admin access to this repo to fix it.

**Comment by sbidoul** [comment]
@Yajo I just gave you admin access.

**Comment by Yajo** [comment]
Note: to apply this workaround: https://github.com/actions/cache/issues/2#issuecomment-673493515

**Comment by sbidoul** [comment]
@yajo while you are at it you may want to look into #18

**Comment by Yajo** [comment]
After merging #19, if you rebase this will probably get fixed.

Otherwise, we can alter the `$CACHE_DATE` secret later, to force cache "clearing", and again it should get fixed.

**Comment by sbidoul** [comment]
Ok, green. Almost there.

**Pull request merged**
