### PR TITLE
Install dependencies with PIP by default

### PR DESCRIPTION
**Pull request by simahawk**
Is not experimental anymore.

### CODE REVIEW

**Review by yajo — APPROVED** [review]
Please check the linter.

**Comment by sbidoul** [comment]
I'm good with this but shouldn't we also change the default ci to GitHub? Travis is kind of deprecated here since we are not going to use it anymore for new repos.

**Comment by simahawk** [comment]
> I'm good with this but shouldn't we also change the default ci to GitHub? Travis is kind of deprecated here since we are not going to use it anymore for new repos.

Yes, my next step :wink:

**Comment by sbidoul** [comment]
What's up with poetry? Any idea,  @yajo ?

**Comment by sbidoul** [comment]
Ah, there was a poetry release a few minutes ago. So you can try capping it to `<1.2` [here](https://github.com/OCA/oca-addons-repo-template/blob/0fc8013f110133d2c33d76133dc6acb0d1a946bb/pyproject.toml#L18).

**Comment by yajo** [comment]
It should require poetry-core instead.

**Pull request closed without merging**
