### PR TITLE
Add question to convert readme fragments to markdown

### PR DESCRIPTION
**Pull request by sbidoul**

### CODE REVIEW

**Comment by francesco-ooops** [comment]
Hi @sbidoul , could it be worth including v16 as well? So for any new module or future migration to v16 the conversion to .md will be already done. 

Would there be a problem with that?

**Review by TumbaoJu — APPROVED** [review]

**Comment by sbidoul** [comment]
@francesco-ooops once this is merged I propose that we run a manual copier update on some selected 16.0 repos first to see how it goes. If if no major problem show up, I can launch a mass update of all 16.0 branches.

**Comment by TumbaoJu** [comment]
@sbidoul : Good idea.

**Review by yajo — APPROVED** [review]
I was thinking about this yesterday. I was waiting for #222 to merge to open this PR actually 😆

**Pull request merged**
