### PR TITLE
Fix prettier installation yet again

### PR DESCRIPTION
**Pull request by Yajo**
I hope https://github.com/prettier/pre-commit/commit/d2e9f0ce87ad6dd21deb8c48e81f92401af92988 is the last chapter of this prettiermaggeddon. At least now the official source is maintained by the pre-commit community, which has more experience on how things work for pre-commit.

### CODE REVIEW

**Review by joao-p-marques — APPROVED** [review]

**Review by TDu — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Do we need again to update all OCA repositories in 13.0 and 14.0?

**Comment by TDu** [comment]
All I know is I needed this to work properly on a sale-workflow branch 13.0 PR today.

**Comment by pedrobaeza** [comment]
Then it seems so :sob:

**Comment by Yajo** [comment]
AFAIK the old https://github.com/prettier/pre-commit should still work... However it's been archived and I just wanted to update this before I forget. Are you sure @TDu that you were using https://github.com/prettier/pre-commit and not https://github.com/prettier/prettier?

**Comment by TDu** [comment]
All I know is after multiple pre-commit uninstall/install/autoupdate. I kept getting this error :
```
An unexpected error has occurred: CalledProcessError: Command: ('/usr/lib/git-core/git', 'reset', 'v1.19.1', '--hard')
Return code: 128
Expected return code: 0
Output: (none)
Errors: 
    fatal: ambiguous argument 'v1.19.1': unknown revision or path not in the working tree.
    Use '--' to separate paths from revisions, like this:
    'git <command> [<revision>...] -- [<file>...]'
    

Traceback (most recent call last):
  File "/home/tducrest/.local/lib/python3.6/site-packages/pre_commit/error_handler.py", line 46, in error_handler
    yield
  File "/home/tducrest/.local/lib/python3.6/site-packages/pre_commit/main.py", line 291, in main
    return run(args.config, store, args)
  File "/home/tducrest/.local/lib/python3.6/site-packages/pre_commit/commands/run.py", line 262, in run
    for hook in all_hooks(config, store)
  File "/home/tducrest/.local/lib/python3.6/site-packages/pre_commit/repository.py", line 221, in all_hooks
    for repo in root_config['repos']
  File "/home/tducrest/.local/lib/python3.6/site-packages/pre_commit/repository.py", line 222, in <genexpr>
    for hook in _repository_hooks(repo, store, root_config)
  File "/home/tducrest/.local/lib/python3.6/site-packages/pre_commit/repository.py", line 197, in _repository_hooks
    return _cloned_repository_hooks(repo_config, store, root_config)
  File "/home/tducrest/.local/lib/python3.6/site-packages/pre_commit/repository.py", line 166, in _cloned_repository_hooks
    manifest_path = os.path.join(store.clone(repo, rev), C.MANIFEST_FILE)
  File "/home/tducrest/.local/lib/python3.6/site-packages/pre_commit/store.py", line 151, in clone
    return self._new_repo(repo, ref, deps, clone_strategy)
  File "/home/tducrest/.local/lib/python3.6/site-packages/pre_commit/store.py", line 127, in _new_repo
    make_strategy(directory)
  File "/home/tducrest/.local/lib/python3.6/site-packages/pre_commit/store.py", line 148, in clone_strategy
    _git_cmd('reset', ref, '--hard')
  File "/home/tducrest/.local/lib/python3.6/site-packages/pre_commit/store.py", line 146, in _git_cmd
    return cmd_output('git', *args, cwd=directory, env=env)
  File "/home/tducrest/.local/lib/python3.6/site-packages/pre_commit/util.py", line 153, in cmd_output
    returncode, cmd, retcode, output=(stdout, stderr),
pre_commit.util.CalledProcessError: Command: ('/usr/lib/git-core/git', 'reset', 'v1.19.1', '--hard')
Return code: 128
Expected return code: 0
Output: (none)
Errors: 
    fatal: ambiguous argument 'v1.19.1': unknown revision or path not in the working tree.
    Use '--' to separate paths from revisions, like this:
    'git <command> [<revision>...] -- [<file>...]
```
And doing the change on ` .pre-commit-config.yaml` mentinonned here fixed the problem.

**Comment by Yajo** [comment]
You're right, bot.

**Comment by sbidoul** [comment]
Is there any urgency to deploy this. AFAICT the previous config still works just fine. I suspect @TDu 's issues where transient ?

**Comment by Yajo** [comment]
No urgency AFAICS. See https://github.com/OCA/sale-workflow/pull/1276/files#r531574038.

**Pull request merged**
