### PR TITLE
Bump pre-commit action version

### PR DESCRIPTION
**Pull request by joao-p-marques**
Fixes https://github.com/OCA/oca-addons-repo-template/issues/99

ping @sbidoul

### CODE REVIEW

**Comment by joao-p-marques** [comment]
@sbidoul can you publish this fix in a new release (and others that were not included yet)?

Also, how can we have access to do the same operation? Which is the PSC team associated to this repo?

**Comment by pedrobaeza** [comment]
@sbidoul can any of us (Joao or me) gain "Settings" access for doing without disturbing you?

**Comment by Yajo** [comment]
Published https://github.com/OCA/oca-addons-repo-template/releases/tag/v1.3.7

**Comment by sbidoul** [comment]
@pedrobaeza @joao-p-marques the PSC for this repo is https://odoo-community.org/psc-teams/community-46. Do not hesitate to apply using the usual process.

**Pull request merged**
