### PR TITLE
Hello world 🖖

### PR DESCRIPTION
**Pull request by yajo**

### CODE REVIEW

**Comment by Yajo** [comment]
@sbidoul Github actions should be triggered in this PR. Could you please see what's happening? Maybe they are disabled in the repo config? :thinking:

**Comment by sbidoul** [comment]
They are enabled:

image

**Comment by Yajo** [comment]
OK, maybe I need to PR from the same repository to be able to develop actions... I'll open another PR from here, at least for this time.

**Comment by Yajo** [comment]
Indeed, ok then I'll close and continue in #2.

**Pull request closed without merging**
