### PR TITLE
[UPD] Upgrde isort, which does not build with the latest poetry release

### PR DESCRIPTION
**Pull request by rousseldenis**
@sbidoul

### CODE REVIEW

**Review by sbidoul — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Is this related to https://github.com/PyCQA/isort/issues/2077 / https://github.com/PyCQA/isort/pull/2078 ?

**Comment by pedrobaeza** [comment]
Potential problem related to this: https://github.com/OCA/l10n-spain/pull/2783#issuecomment-1408362058

**Comment by rousseldenis** [comment]
> Is this related to [PyCQA/isort#2077](https://github.com/PyCQA/isort/issues/2077) / [PyCQA/isort#2078](https://github.com/PyCQA/isort/pull/2078) ?

Yes

**Comment by rousseldenis** [comment]
Mmmh apparently not sufficent

**Comment by rousseldenis** [comment]
I changed the url too as I think the former repository has not actual version yet

**Comment by yajo** [comment]
It's missing the real fix in the template.

**Comment by yajo** [comment]
full fix: https://github.com/OCA/oca-addons-repo-template/pull/184

**Pull request closed without merging**
