### PR TITLE
[IMP] add fail for en.po files

### PR DESCRIPTION
**Pull request by etobella**
Adds changes for #176

### CODE REVIEW

**Comment by etobella** [comment]
@sbidoul setting python 3.6 failedgithub.com:tegin/oca-addons-repo-template.git due to the change of the default machine of ubuntu on github actions, as you can see here:
https://github.com/actions/setup-python/issues/544

Last commit changes fixed it. Also, if we reexecute master now, it will fail without the last commit changes :cry: 
https://github.com/OCA/oca-addons-repo-template/actions/runs/3468866261/jobs/6204635946

**Comment by sbidoul** [comment]
Let's pin ubuntu-20.04 for 10.0 too. And 22.04 for 14-16?

**Comment by etobella** [comment]
@sbidoul Done!

**Review by sbidoul — APPROVED** [review]

**Comment by sbidoul** [comment]
Thanks @etobella. I'm launching a mass update of branches 14, 15, 16 and removing en.po files at the same time.

Would you mind doing a similar PR in https://github.com/OCA/oca-addons-repo-template/tree/v1.12.0/version-specific for branche 10 - 13 ?

**Pull request merged**
