### PR TITLE
imp: Odoo <14.0: pin black click dependency to <8.1.0 - Odoo >=14.0: bump black to 22.3.0

### LINKED ISSUE #133: pre-commit: Black < 22 is incompatible with click 8.1.0
## Module
.pre-commit-config.yaml

## Describe the bug
When running pre-commit in [web](https://github.com/OCA/web/blob/15.0/.pre-commit-config.yaml) we get the following exception:
```
black....................................................................Failed
- hook id: black
- exit code: 1
Traceback (most recent call last):
  File "/home/oca-precommit/.cache/pre-commit/repov0kwiinn/py_env-python3/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "/home/oca-precommit/.cache/pre-commit/repov0kwiinn/py_env-python3/lib/python3.8/site-packages/black/__init__.py", line 6606, in patched_main
    patch_click()
  File "/home/oca-precommit/.cache/pre-commit/repov0kwiinn/py_env-python3/lib/python3.8/site-packages/black/__init__.py", line 6595, in patch_click
    from click import _unicodefun  # type: ignore
ImportError: cannot import name '_unicodefun' from 'click' (/home/oca-precommit/.cache/pre-commit/repov0kwiinn/py_env-python3/lib/python3.8/site-packages/click/__init__.py)
```

## To Reproduce
**Affected versions**:
* black < 22
* click 8.1.0

1. run a fresh install of pre-commit with pre-commit config from [web](https://github.com/OCA/web/blob/15.0/.pre-commit-config.yaml)

**Expected behavior**
pre-commit should be runnable without exceptions in its dependencies if the code is ok

**Additional context**
see https://github.com/psf/black/issues/2964
as this problem most likely not only affects web, i opened the issue here to have the solution propagated to all oca addons repos

### PR DESCRIPTION
**Pull request by Tardo**
Fix #133 

- <14.0: pin black click dependency
- \>=14.0: bump black to 22.3.0

### CODE REVIEW

**Review by HaraldPanten — APPROVED** [review]
Pre-commit is failing due to the issue that this PR is trying to solve. I think we can excepcionally ignore the pre-commit failure

**Review by pedrobaeza — APPROVED** [review]

**Comment by sbidoul** [comment]
Thanks! I tagged and released.

**Comment by sbidoul** [comment]
Example here: https://github.com/OCA/mis-builder/pull/426
Some noise due to black removing python 2 unicode string prefixes.

**Comment by pedrobaeza** [comment]
Thanks. Are we going to apply it massively?

**Comment by sbidoul** [comment]
> Thanks. Are we going to apply it massively?

I can do that later this week when we've got some feedback on the release.

**Comment by pedrobaeza** [comment]
OK, we have to take into account that all CIs will be red for 14.0 and 15.0 meanwhile. I will update some repos applying manually the template.

**Comment by sbidoul** [comment]
I'm deploying to all repos, 13, 14, 15.

At first sight there are some pylint failures due to `[W7940(dangerous-view-replace-wo-priority), ]  Dangerous use of "replace" from view with priority 0 < 99`. I'm not sure when this check became mandatory.

**Comment by sbidoul** [comment]
In the meantime, click 8.1.1 is out, which resolves the issue :man_shrugging:

**Comment by Tardo** [comment]
@sbidoul v8.1.1 gives the same problem as far as I have checked.

https://click.palletsprojects.com/en/8.1.x/changes/#version-8-1-1

**Comment by gurneyalex** [comment]
trying https://github.com/OCA/server-auth/pull/365

**Comment by sbidoul** [comment]
My mass update script crashed at the letter `o`. It's been restarted now.

**Pull request merged**
