### PR TITLE
[FIX] Upgrade maintainer-tools

### PR DESCRIPTION
**Pull request by lmignon**
Includes fix for issue when installing docutils dependency.
docutils 0.15.1-post1 has installation issues with pip.
see pypa/pip#9203 (comment)

see https://travis-ci.com/github/OCA/wms/jobs/457408267#L297

### CODE REVIEW

**Review by joao-p-marques — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]

**Review by Yajo — APPROVED** [review]

**Comment by sbidoul** [comment]
I have tagged v1.1.0. People who want to apply it can simply run `copier -f update`. I'll deploy to all repos as soon as I can.
Note this release includes the move from travis to gha for the pre-commit step.

**Comment by Yajo** [comment]
Do you think that it would be a good idea to add a workflow that, when doing a release, pushes it to all repos in supported branches (13.0 and 14.0 ATM)?

**Comment by sbidoul** [comment]
Sure an automation is needed, trust me it's not particularly fun to run it manually :). Making it robust is not entirely trivial. I'm polishing the script a little bit each time I run it. Unless something already cooked exists that I don't know?

**Comment by Yajo** [comment]
> Unless something already cooked exists that I don't know?

Nope, but I could draft it to let you put your script logic over it.

**Comment by dreispt** [comment]
@sbidoul Thanks, if repo maintainers are informed, I think they can take this in their hands.

**Comment by Yajo** [comment]
@dreispt IMHO automation is a better option.

**Pull request merged**
