### PR TITLE
[FIX] pylint-odoo: usable under python 3.10

### PR DESCRIPTION
**Pull request by Yajo**
Fixes https://github.com/OCA/oca-addons-repo-template/issues/127

### CODE REVIEW

**Review by moylop260 — APPROVED** [review]
👍

**Review by Tardo — APPROVED** [review]

**Comment by Tardo** [comment]
:+1: Tested. Thanks!

**Comment by sbidoul** [comment]
If we don this, can we / should we remove the [python version pinning here](https://github.com/OCA/oca-addons-repo-template/blob/ee62ad0be6c5c79c3b51bea4328b171fd7e9d75c/src/.github/workflows/pre-commit.yml.jinja#L19-L24) ?

**Comment by Yajo** [comment]
So it seems.

**Comment by Yajo** [comment]
Fixed now.

**Pull request merged**
