### PR TITLE
[FIX] Update flake8 repo

### PR DESCRIPTION
**Pull request by yajo**
Apply the same as a48f386b41ff9dbdab7125e3a362b8eaae5b1af6 but for the projects.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Hehe, I opened #171 mostly at the same time. Closing mine.

**Review by ap-wtioit — APPROVED** [review]

**Comment by pedrobaeza** [comment]
The CI is failing with the same gitlab.com reference. Do you know why?

**Comment by simahawk** [comment]
FTR same probl here https://github.com/OCA/edi/pull/686

**Comment by ap-wtioit** [comment]
@yajo if you have the time, can you also fix https://github.com/OCA/oca-addons-repo-template/blob/master/version-specific/13.0/.pre-commit-config.yaml.jinja in your pull request, i think the tests will be fine then

**Comment by yajo** [comment]
I published https://github.com/OCA/oca-addons-repo-template/releases/tag/v1.11.1 because I guess everybody will hit this problem the next days.

**Pull request merged**
