### PR TITLE
[IMP] run oca-gen-addon-readme in pre-commit

### PR DESCRIPTION
**Pull request by ap-wtioit**
This should make it clearer that changes in README.rst are lost if not
 made to the proper readme/*.rst
 
 Info @wt-io-it

### CODE REVIEW

**Comment by pedrobaeza** [comment]
That was not done, because it requires you to have locally such tool and the dependencies, so it's more startup burden.

**Comment by ap-wtioit** [comment]
@pedrobaeza isn't it already installed with
```
  - repo: https://github.com/oca/maintainer-tools
    rev: dfba427ba03900b69e0a7f2c65890dc48921d36a
```
in .pre-commit-config.yaml?

**Comment by pedrobaeza** [comment]
Oh, it can be... I let the experts in this file to say then.

**Review by joao-p-marques — APPROVED** [review]
LGTM from code review :+1:

**Review by Yajo — APPROVED** [review]

**Comment by sbidoul** [comment]
There is a problem with this PR.: the maintainer tools version we need to use for this need to be identical to [the one used by the oca-github-bot](https://github.com/OCA/oca-github-bot/blob/daaf1747ca15eab945cec4a97a0919c3c66dd686/Dockerfile#L32), until we find a way to not regenerate all readme files each time the script evolves (https://github.com/OCA/maintainer-tools/issues/520)

So I'm reverting. Can you re-do it with a separate repo entry using the correct maintainer-tools commit ?

Also, note that, similar to #93, the CI check will not error out if the README.rst was not generated by the PR author.

**Pull request merged**
