### PR TITLE
Copier updated

### PR DESCRIPTION
**Pull request by yajo**
- Use newer python versions.
- Add extra older python versions when required by the hooks.
- Fix tests.
- Unpin in `pyproject.toml`, so all you need to update the lockfile is to run `poetry update` from now on.

Closes #158.

### CODE REVIEW

**Comment by yajo** [comment]
This is now ready to merge IMHO. Please @sbidoul could you review?

**Comment by sbidoul** [comment]
Thanks. About .gitignore: do you confirm copier supports the symlink? Why not doing different files instead? What we ignore in the template is unrelated to what we ignore in the template itself.

**Review by sbidoul — COMMENTED** [review]
Just a question about .gitignore.

**Comment by yajo** [comment]
If you prefer we can have separate files, but I have tested that this works as expected in both scenarios.

**Pull request merged**
