### PR TITLE
Switch to prettier/pre-commit repo

### PR DESCRIPTION
**Pull request by sbidoul**
The prettier/prettier hook is broken and incompatible with pre-commit 2.8+. Switch to prettier/pre-commit.

See also https://github.com/pre-commit/pre-commit/issues/1674

### CODE REVIEW

**Comment by sbidoul** [comment]
cc/ @feketemihai

**Review by feketemihai — APPROVED** [review]

**Comment by sbidoul** [comment]
I'll push the update to the 14.0 branches tomorrow. And I'll need to see what to do with 13.0.

**Comment by pedrobaeza** [comment]
The node version pinning was not enough?

**Review by pedrobaeza — APPROVED** [review]

**Comment by sbidoul** [comment]
> The node version pinning was not enough?

This is a different issue, unfortunately.

**Review by rvalyi — CHANGES_REQUESTED** [review]
Hello @sbidoul, I had the prettier issue yesterday trying to migrate l10n_fr_siret: 
https://travis-ci.com/github/OCA/l10n-france/jobs/423374062#L318

I then applied your patch to try it. This fixed the NodeJS issue. However, I noticed something strange, suddenly the pre-commit was re-indentig the XML files aggressively again as you can see in the new Travis run:
https://travis-ci.org/github/akretion/l10n-france/jobs/740599061

This all looks like if the .prettierrc.yml configuration or at least the `xmlWhitespaceSensitivity: "ignore"` setting was ignored.
it is present in the PR still as you can see https://github.com/akretion/l10n-france/blob/14.0-mig-l10n_fr_siret/.prettierrc.yml

So it seems this fix breaks https://github.com/OCA/oca-addons-repo-template/pull/35 again.
Can anyone confirm?

**Comment by sbidoul** [comment]
@rvalyi the behavior looks correct. #35 is actually setting xmlWhitespaceSensitivity to strict and you don't have it in your PR.

**Comment by sbidoul** [comment]
I applied this as a patch to 13.0 branches. Now merging to test copier update on a few 14.0 branches.

**Comment by rvalyi** [comment]
wow, that's right the #35 patch was not in my PR, I read too fast, sorry for the noise, I'll re-test as soon as it is deployed. Thanks.

**Pull request merged**
