### PR TITLE
[IMP] upgrade pylint version to 9.0.4 to support Odoo 17.0

### PR DESCRIPTION
**Pull request by celm1990**
see https://github.com/OCA/pylint-odoo/pull/477

@pedrobaeza @sbidoul could you please review this?

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by sbidoul** [comment]
This change applies to 16 too. Do we risk making existing 16.0 branches red due to this?

**Comment by celm1990** [comment]
> This change applies to 16 too. Do we risk making existing 16.0 branches red due to this?

@sbidoul but for 16 it is working, because 16.0 already is into `DFTL_VALID_ODOO_VERSIONS` https://github.com/OCA/pylint-odoo/blob/d5888089eac660ebb6c06f33e3ed5655c409eb72/src/pylint_odoo/misc.py#L19-L33

**Comment by celm1990** [comment]
@sbidoul, my apologies for the confusion. I have revised the code to align with your reference.

**Comment by yajo** [comment]
> Do we risk making existing 16.0 branches red due to this?

Is this question really relevant today?

In old times, when linting was centralized in MQT, a single update there could set many branches red.

Now with the copier template, you only break things _if_ and _when_ you update the template in a branch. At that moment in time, you have the chance to apply auto or manual fixes, and then push the new green branch that satisfies any new rules.

So, do we really need to care that much now about backwards compatibility? 🤔

**Comment by sbidoul** [comment]
> Is this question really relevant today?

I think it is. Sometimes we need to do a mass update (like we recently did for 14, 15, 16, which caused a lot of troubles).

I think we must reach a situation where the list of lint checks is explicit and not dependent of the specific version of the linters.

**Comment by celm1990** [comment]
@sbidoul  Can we get this merged, at least for new repositories (from OCA or personal ones)? I understand that a mass update to existing OCA repositories may not necessarily occur. Is there anything we can improve in the pull request (PR) to facilitate the merge?

**Pull request merged**
